version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: smash-hits-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: root1234!
      POSTGRES_DB: smash-hits
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
volumes:
  postgres-data:
